spring.application.name=foody
#spring.profiles.active=local
spring.profiles.active=h2,sample

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 공유 DB라서 create 금지 (테이블이 통째로 삭제됨)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always