spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

board:
  cache:
    ttl-seconds: 600

  jwt:
    secret: ${JWT_SECRET}
    access-expire-minutes: 30
    refresh-expire-days: 7

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never